name: shoesapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/startpages/
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf



